{% set name = "stochatreat" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad764601df9ac449761050bfc4e15656113199733efe48f9a38dca43b72b1537
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - typing
    - pandas
    - numpy
  run:
    - python >=3.5
    - pip
    - setuptools
    - typing
    - pandas
    - numpy

test:
  imports:
    - stochatreat
  requires:
    - pytest

about:
  home: http://github.com/manmartgarc/stochatreat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python module for block randomization using pandas'

  description: |
    stochatreat is a Python module to employ block randomization using pandas.
    Mainly thought with RCTs in mind, it also works for any other scenario in
    where you would like to randomly allocate treatment within blocks or strata.
  dev_url: https://github.com/manmartgarc/stochatreat

extra:
  recipe-maintainers:
    - royalts
