{% set name = "stochatreat" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 852ba3230fbe2e649948d7b5f6cdab419a51df8202f5285792180dba6ff9d021
build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pandas
    - numpy
  run:
    - python >=3.6
    - pip
    - setuptools
    - pandas
    - numpy

test:
  imports:
    - stochatreat

about:
  home: http://github.com/manmartgarc/stochatreat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python module for block randomization using pandas'

  description: |
    stochatreat is a Python module to employ block randomization using pandas.
    Mainly thought with RCTs in mind, it also works for any other scenario in
    where you would like to randomly allocate treatment within blocks or strata.
  dev_url: https://github.com/manmartgarc/stochatreat

extra:
  recipe-maintainers:
    - royalts
