travis:
  secure:
    BINSTAR_TOKEN: UID4qBJA9+knvUAiMND1oQ/RnU6d/vRC7ga0UdfkbP8o62x6M+EctD0HYOUM4GCF9kIqlNej5N/PimFeGPuimYLRLDbXoO2ahpKNQMWE10BCb6rXkgd/E6jguA7PVivGlr0kCs59Coz9RVH3lomt2ogPIJPkyUqyvAUqulmvtqtvyQ3TyBb5iafb19QdUcRb2Qk48/Qe1Nih4ZXIM20fHyXfZSlgWlp/YcRZjjOFH9cvy14AZ2iN00oZl1JTKtuv2AyKJerSzkLRN64u98iRfiq9vSCa+cBjIRjZnxQLo5TOgl8rk2unLDYBXJjygB3ihjkJ6hjUsilvBUSB7edzD6pGHBIwySCXLEHlvq1qBsSne6/xOibnawpdfIa3QFWld972SHsktc8XKsCTlX2p5LVqiXIaJosJ90aOruetjnozF/L9FSe6037YZcPd4HXO0Psm1tlzzj5t1r+e7MGqb0hPxYzBOZAavr7NkvzNi+nvTkZCuaaOTjTDrqsCS3FU9KfI/JVCXP3mkCB+JkCgJfuMJNJMyKVi+S0/lFwYDpfg4T8wFkd98b65SJEBZfkWq1Gmv6bWgYt0X/iW4KjPwPAJKN3lTLjesy+ieotbSAYsutBUK5bjBw95dkFFsrKedPcEKp+QOdYRhS+1YHjd3E0FnI96tPj+BevsbGhEZK0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
